Week two git slides
RoboJackets/software-training pull request #15
Opened 2017-07-09 03:50 UTC by joshhting

2017-07-09 04:18 UTC, jgkamat requested changes
Overall looking great! Nice job! :tada:

2017-07-09 04:18 UTC, jgkamat commented on slides/week2/git.org
> +- Reminder: a fork is an independently maintained repository based off of another
Maybe you can just say 'a fork is a (deep) copy of another git repository'

'based off of another' feels weird and can be confusing

2017-07-09 04:18 UTC, jgkamat commented on slides/week2/git.org
> +    git <command> <param1> <param2> ...
do you want me to make `git` a special keyword so it turns green? That would be pretty cool :P

2017-07-09 04:18 UTC, jgkamat commented on slides/week2/git.org
> +- We can keep our fork up to date with the /git pull/ command
`/` should probably be `~`

2017-07-09 04:18 UTC, jgkamat commented on slides/week2/git.org
> +# | [[file:https://i.imgur.com/k0Llu0s.png]] | [[file:https://i.imgur.com/8vCOZQP.png]] |
:100:

2017-07-09 04:18 UTC, jgkamat commented on slides/week2/git.org
> +# Basically say that this is outside the scope of the current lesson and if they want to read up on it on their own we won't stop them
I think that if the remote branch is the same as the local, you can specify `git pull upstream`. That depends on your gitconfig though (`push.default`), so I would lean towards keeping it this way. Just letting you know that could be an option if we want to ignore branches completly right now.

2017-07-09 04:18 UTC, jgkamat commented on slides/week2/git.org
> +- Git encapsulates changes in "commits"
This sounds a little confusing, maybe:

Git calls every version it stores a 'commit'

2017-07-09 04:18 UTC, jgkamat commented on slides/week2/git.org
> +      - This does mean that you should never commit things like passwords to
Also add a bullet about large files :)

2017-07-09 04:18 UTC, jgkamat commented on slides/week2/git.org
> +- Anything  commited to git stays in git.
kind of a lie, but I'd excuse it for newcomers. If there's a better way of wording this that doesn't imply you can never change history I think we should go with that.

Case study: Someone creates a branch, puts important work on it, and deltes it. Then they wait 30d and it gets garbage collected, and they want their work back. According to this slide, they should be able to, but in reality, they can't.

2017-07-09 04:18 UTC, jgkamat commented on slides/week2/git.org
> +    git add .
No one will see the `.` at first. Maybe add a line comment above it with something like

`# git add <PERIOD>`

I thnk `git add -A` would work too, but not sure.

2017-07-09 04:18 UTC, jgkamat commented on slides/week2/git.org
> +- /-m "..."/: Commits require commit messages to label them
We should also make sure we tell them `-<letter>` and `--<word>` are ways for specifying options for cli programs. I'm not sure if we covered this earlier though.

2017-07-09 14:29 UTC, kberzinch commented
This is supposed to merge into `weekTwo` not `master`.

2017-07-09 20:43 UTC, joshhting commented on slides/week2/git.org
> +    git <command> <param1> <param2> ...
That'd be neat

2017-07-09 21:45 UTC, jgkamat commented
You probably also want to update the README to add these slides.

2017-07-09 23:31 UTC, kberzinch commented
I have a tangentially related nitpick - week 1 git slides were `github.org`, this week they're `git.org`. I propose we standardize on one or the other.

2017-07-09 23:32 UTC, kberzinch commented on slides/week2/git.org
> +- We can keep our fork up to date with the /git pull/ command
Seconded

2017-07-09 23:33 UTC, kberzinch commented on slides/week2/git.org
> +- /-m "..."/: Commits require commit messages to label them
also bumping same tweak from earlier - use `~` instead of `/` for command snippets

2017-07-09 23:36 UTC, kberzinch requested changes
Typo

2017-07-09 23:36 UTC, kberzinch commented on slides/week2/git.org
> +- /master/: Name of the branch to push to(Still top secret material)
Missing a space before the last open parenthesis

2017-07-09 23:41 UTC, joshhting commented
I'll rename the week 1 file to git.org then.

2017-07-11 01:12 UTC, JasonGibson274 commented on slides/week2/git.org
> +      - ~upstream~: specify that we are pulling from the upstream repository
Just a note. Last week they named their upstream rj.

2017-07-11 06:57 UTC, jgkamat submitted a review, later dismissed
Have a few nitpicks, but everything else looks good so conditional :+1:

2017-07-11 06:57 UTC, jgkamat commented on slides/week2/git.org
> +  - Git will refuse to push files larger than 100 MB.
Er, this isn't actually part of git. This is a limitation of github. Git will commit/push such files just fine (but might be slow). For example, [gitlab has a 10gb overall limit](https://about.gitlab.com/2015/04/08/gitlab-dot-com-storage-limit-raised-to-10gb-per-repo/) (and no hard per-file limit).

2017-07-11 15:50 UTC, kberzinch approved these changes

2017-07-11 16:03 UTC, jgkamat approved these changes

2017-07-11 17:29 UTC, merged