Jason/project1.4
RoboJackets/software-training pull request #152
Opened 2020-09-06 19:23 UTC by JasonGibson274

This contain a write up and simple exercises where the students will run a google Colab notebook in order to train a simple NN on the MNIST dataset. They will then play around with some parameters (learning rate and epochs). Finally they apply it to KMNIST.

I think overall this is a little short.

2020-09-08 19:55 UTC, kylestach commented on assignments/week_1/project1.4/ReadMe.md
> +classify images of handwritten digits into what it is. We will be using a
`The goal is to classify images of handwritten digits into the digits they represent`?

2020-09-11 00:19 UTC, kylestach requested changes

2020-09-11 00:19 UTC, kylestach commented on assignments/week_1/project1.4/ReadMe.md
> +convolutional neural network in order to effectively process the image data.
Tie in to convolutions project!

2020-09-11 00:19 UTC, kylestach commented on assignments/week_1/project1.4/ReadMe.md
> +using the button at the top pictured here in order to make it easier on yourself.
Pictured where?

2020-09-11 00:19 UTC, kylestach commented on assignments/week_1/project1.4/ReadMe.md
> +it and I barely know how it works).
This does not ~spark joy~ inspire confidence.

2020-09-11 00:19 UTC, kylestach commented on assignments/week_1/project1.4/ReadMe.md
> +You should see a graph similar to the one below at the final output.
??

2020-09-11 00:19 UTC, kylestach commented on assignments/week_1/project1.4/ReadMe.md
> +accurate model the data (trust me on this one). So what else could we look at in order to
Describe this first dataset

2020-09-11 00:19 UTC, kylestach commented on assignments/week_1/project1.4/ReadMe.md
> +accurate model the data (trust me on this one). So what else could we look at in order to
And also maybe describe the model

2020-09-11 00:19 UTC, kylestach commented on assignments/week_1/project1.4/ReadMe.md
> +how we discussed underfitting the model previously. Now our model has enough room to
Uh, where did you discuss this?

Also, maybe it would be good to give people intuition for over/underfit by fitting a polynomial to some data. Something like this?

![image](https://user-images.githubusercontent.com/9097872/92522161-60648e00-f1ec-11ea-8083-34954585f2fd.png)

2020-09-11 00:21 UTC, JasonGibson274 commented on assignments/week_1/project1.4/ReadMe.md
> +how we discussed underfitting the model previously. Now our model has enough room to
You keep having better graphics than me. I'm impressed and happy.

2020-09-11 01:49 UTC, JasonGibson274 commented on assignments/week_1/project1.4/ReadMe.md
> +it and I barely know how it works).
I think it gets the point across of you don't need to understand the entire script.

2020-09-18 00:52 UTC, kylestach approved these changes

2020-09-18 00:52 UTC, merged