Week four example code
RoboJackets/software-training pull request #35
Opened 2017-07-26 09:15 UTC by JasonGibson274

I just wanted to open this up for review early. I was planning on adding more to the pointer section to get more depth in examples.

2017-07-28 18:55 UTC, JasonGibson274 commented
I will remove some of the explanation depending on the topic slides but if you want any removed just comment. I know this throws a compiler warning with returning a pointer to a local variable but the first time I learned what a pointer was I made this exact mistake so I think it is worth covering explicitly. I can also remove the vector of pointers if looks to confusing.

2017-07-29 18:36 UTC, kberzinch requested changes
Other than that, looks good to me!

2017-07-29 18:36 UTC, kberzinch commented on code/week4/week4.cpp
> +	// see why -> exists, Thanks Dennis Ritchie for having an eye for sytle
style

2017-07-29 19:27 UTC, kberzinch approved these changes

2017-07-31 21:03 UTC, merged