Week five topic slides
RoboJackets/software-training pull request #36
Opened 2017-07-29 21:52 UTC by kberzinch

The Trello card on this was really brief - I fleshed out what I could think of but this still seems really short.

Advice on expanding this deck somewhat is appreciated.

2017-07-30 05:41 UTC, JasonGibson274 reviewed
I would have some examples of polymorphism, inheritance and how/why we group methods and variables together in different classes.

2017-08-01 03:35 UTC, jgkamat requested changes
Overall looking pretty good, but needs a few changes.

2017-08-01 03:35 UTC, jgkamat commented on slides/week5/week5.org
> +* Why bother?
Maybe you could discuss code reuse a bit here

2017-08-01 03:35 UTC, jgkamat commented on slides/week5/week5.org
> +#+BEGIN_SRC c
These should be `C++` not `c` (they produce compiler errors, and don't recognize C++ only keywords in highlighting).

2017-08-01 03:35 UTC, jgkamat commented on slides/week5/week5.org
> +        int getB() { return b; }
maybe show a `getAPlusB` method to show how it actually is working

2017-08-01 03:35 UTC, jgkamat commented on slides/week5/week5.org
> +#+BEGIN_SRC c
Maybe:
```
- Now we can create =child= objects with all the properties of an =example= object
- This means we can safely cast a =child= object to an =example= object
  #+BEGIN_SRC C++
    child c;
    example& e = dynamic_cast<example&>(c);
  #+END_SRC
- But we can't go the other way
  #+BEGIN_SRC C++
    example e;
    child& c = dynamic_cast<child&>(e);
  #+END_SRC

  #+BEGIN_EXAMPLE
    example.cpp: In function ‘int main()’:
    example.cpp:20:38: error: cannot dynamic_cast ‘e’ (of type ‘class example’) to type
    ‘class child&’  (source type is not polymorphic)
         child& c = dynamic_cast<child&>(e);
  #+END_EXAMPLE
```

2017-08-01 03:37 UTC, kberzinch commented on slides/week5/week5.org
> +        int getB() { return b; }
Ooh, I like that

2017-08-01 03:38 UTC, kberzinch commented on slides/week5/week5.org
> +#+BEGIN_SRC c
I tried that but the bullet point in the middle didn't line up with the rest of them and it looked kind of dumb

2017-08-01 04:28 UTC, jgkamat commented on slides/week5/week5.org
> +#+BEGIN_SRC c
Hmm, that's weird. This is what I get, fwiw.

![2017-07-31-212722_1920x1080_scrot](https://user-images.githubusercontent.com/4349709/28809245-376a4484-76bd-11e7-83d0-32077eb5d77b.png)

2017-08-01 18:59 UTC, sastorer commented
@kberzinch When you talk about what a class is, one of the best metaphors to use is that classes are like instructions/blueprints sent to a factory to build a lot of the same thing. "Definitions for objects" is a little vague. I feel like you can flesh out that slide more.

2017-08-01 19:02 UTC, sastorer commented on slides/week5/week5.org
> +        int getB() { return b; }
Major plus 1 on this. The slide on inheritance is hella vague.

2017-08-01 19:03 UTC, sastorer commented on slides/week5/week5.org
> +* Why bother?
+1

2017-08-02 01:04 UTC, kberzinch commented on slides/week5/week5.org
> +        int getB() { return b; }
Added

2017-08-02 01:04 UTC, kberzinch commented on slides/week5/week5.org
> +* Why bother?
I added a bullet point but I'm not a fan of the phrasing. Suggestions appreciated.

2017-08-02 01:07 UTC, kberzinch commented on slides/week5/week5.org
> +#+BEGIN_SRC c
OHHH I see what you did there. Fixed and pushed!

2017-08-02 06:33 UTC, jgkamat requested changes
The content here looks mostly good to me, but there needs to be more content explaining what an object and what a class is (and what's the difference). I think the existing example jumps into code too early.

2017-08-02 06:33 UTC, jgkamat commented on slides/week5/week5.org
> +* Why bother?
Maybe: "Additional functionality can be added with minimal extra code using inheritance"?

2017-08-03 00:18 UTC, kberzinch commented on slides/week5/week5.org
> +* Why bother?
I like it - added

2017-08-03 04:08 UTC, jgkamat submitted a review, later dismissed
Overall, I think that the content of the slides looks good to me, but it still feels confusing for a newcomer. This topic is really hard though, so we should just focus on answering questions imo.

2017-08-03 18:04 UTC, JasonGibson274 requested changes
Overall looks good to me.

2017-08-03 18:04 UTC, JasonGibson274 commented on slides/week5/week5.org
> + - It doesn't share any data with other objects
I feel like this is misleading. Objects can share data with other objects. Perhaps something like "Objects of the same class share the same schema of data but the actual values stored are independent instance to instance"

2017-08-03 19:19 UTC, JasonGibson274 commented
Actually we are missing the virtual keyword explanation.

2017-08-04 00:52 UTC, kberzinch commented
Added @JasonGibson274

2017-08-04 01:29 UTC, JasonGibson274 submitted a review, later dismissed

2017-08-05 05:44 UTC, jgkamat submitted a review, later dismissed

2017-08-07 18:36 UTC, joshhting commented on slides/week5/week5.org
> +- For when you want data or functions to be part of your class, but they don't need to be "attached" to an instance of the class
This wording seems a little more confusing than explicitly saying that all instances of a class read from and write to the same static variable

2017-08-07 22:55 UTC, kberzinch commented on slides/week5/week5.org
> +- For when you want data or functions to be part of your class, but they don't need to be "attached" to an instance of the class
Added.

2017-08-08 01:42 UTC, joshhting approved these changes

2017-08-08 01:45 UTC, merged