Week 1 final fixes
RoboJackets/software-training pull request #67
Opened 2017-09-13 06:04 UTC by joshhting

- [x] Add Matthew Woodward's introduction slide

2017-09-13 19:24 UTC, jgkamat submitted a review, later dismissed
LGTM so far

2017-09-15 04:21 UTC, jgkamat submitted a review, later dismissed
LGTM

2017-09-15 04:21 UTC, jgkamat commented on slides/week1/week1.org
> +Copy/paste are generally ctrl+shift+ctrl+shift+v but varies by shell.
ctrl+shift+{c,v}

2017-09-16 00:56 UTC, kberzinch commented on slides/week1/week1.org
> +Copy/paste are generally ctrl+shift+ctrl+shift+v but varies by shell.
oh geez how did that happen

2017-09-16 01:43 UTC, JasonGibson274 commented on slides/week1/git.org
> +    - Run ~sudo apt-get install git~
do we want to use apt instead of apt-get

2017-09-16 01:46 UTC, JasonGibson274 requested changes
overall very good just a small change

2017-09-16 01:46 UTC, JasonGibson274 commented on slides/week1/week1.org
> +| =echo= | Echoes back anything you pass |
Using the word in the definition. Perhaps something like 

 echo - Write arguments to the standard output

2017-09-18 17:48 UTC, joshhting commented
If no complaints I'm going to merge this before our first meeting at 6 today.

2017-09-18 17:49 UTC, JasonGibson274 approved these changes

2017-09-18 18:54 UTC, jgkamat approved these changes
lets get this in more than an hour before pleaseeee

2017-09-18 20:26 UTC, jgkamat commented
Melpa is having some infrastructure problems, which I don't think will affect us, but I want to merge these early so I can do a manual deploy if needed. We can follow up with another PR if anyone is :-1:

2017-09-18 20:26 UTC, merged